<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Tumuku" failures="1" tests="3" name="IETest" time="89.992" errors="0" timestamp="2024-10-07T16:11:56 IST">
  <testcase classname="com.mystore.testcases.LoginPageTest" name="loginTest" time="19.015"/>
  <testcase classname="com.mystore.testcases.LoginPageTest" name="loginTest" time="5.194">
    <failure type="java.lang.AssertionError" message="expected [https://gw.lightinthebox.com/newv/en/user/orders?type=0&amp;amp;location=REALTIME] but found [https://gw.lightinthebox.com/signin?src=mainLoginLink&amp;amp;targetUrl=https%3A%2F%2Fgw.lightinthebox.com%2Findex.php%3Fmain_page%3Daccount]">
      <![CDATA[java.lang.AssertionError: expected [https://gw.lightinthebox.com/newv/en/user/orders?type=0&location=REALTIME] but found [https://gw.lightinthebox.com/signin?src=mainLoginLink&targetUrl=https%3A%2F%2Fgw.lightinthebox.com%2Findex.php%3Fmain_page%3Daccount]
at com.mystore.testcases.LoginPageTest.loginTest(LoginPageTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="com.mystore.testcases.LoginPageTest" name="loginTest" time="0.0">
    <skipped/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- IETest -->
